name: publish

on:
  release:
      types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: envs/hydromt-min.yml
          python-version: "3.9"
          activate-environment: hydromt-min

      - name: Publish to PyPi
        env:
            FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
            FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
            flit publish