name: publish pypitest

on:
  release:
    types: [published]
  # allows running the workflow manually
  workflow_dispatch:

jobs:
  check_version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: envs/hydromt-dev.yml
          activate-environment: hydromt-dev

      - name: Install hydromt
        run: pip install .

      - name: Get hydromt version
        run: echo "PYTHON_VERSION=$(python -c 'from hydromt import __version__ as v; print(f'v{v}')" >> $GITHUB_ENV
      
      - name: Get git tag version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check if tag and package versions match
        uses: nick-fields/assert-action@v1
        with:
          expected: ${{ env.RELEASE_VERSION }}
          actual: ${{ env.PYTHON_VERSION }}
          comparison: exact

  publish:
    runs-on: ubuntu-latest
    needs: check_version
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit>=3.2.0

      - name: Build package
        run: flit build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true